import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // roadmapSidebar: ["{ type: "autogenerated", dirName: "." }"],

  roadmapSidebar: [
    "start",
    {
      type: "category",
      label: "1. Produkt",
      items: [
        "1 Produkt/problem-finden",
        "1 Produkt/idee-ausarbeiten",
        "1 Produkt/recherche",
        "1 Produkt/idee-testen",
        "1 Produkt/prototyp-bauen",
        "1 Produkt/coding",
        "1 Produkt/product-market-fit",
        "1 Produkt/geschäftsmodell",
      ],
    },
    {
      type: "category",
      label: "2. Team",
      items: [
        "2 Team/gründungsteam-aufstellen",
        "2 Team/anteile-verteilen",
        "2 Team/hilfe-finden",
        "2 Team/mitarbeiter-anstellen",
        "2 Team/leadership",
      ],
    },
    {
      type: "category",
      label: "3. Growth",
      items: [
        "3 Growth/ziele-definieren",
        "3 Growth/wie-kann-ich-wirken",
        "3 Growth/soziale-startups",
        "3 Growth/marketing",
        "3 Growth/pr",
        "3 Growth/sales",
      ],
    },
    {
      type: "category",
      label: "4. Finanzierung",
      items: [
        "4 Finanzierung/förderungen",
        "4 Finanzierung/pitchen",
        "4 Finanzierung/investoren",
      ],
    },
    {
      type: "category",
      label: "5. Gründung",
      items: [
        "5 Gründung/unternehmensform",
        "5 Gründung/u18-ü18-gründen",
        "5 Gründung/konto",
        "5 Gründung/buchhaltung-steuern",
      ],
    },
    {
      type: "link",
      label: "Learn to learn",
      href: "https://www.youtube.com/watch?v=O96fE1E-rf8&t=619s",
    },
    {
      type: "link",
      label: "Ressources",
      href: "https://joels-code.notion.site/Channels-Courses-6cf8fd0683e447d988538d745ff202ac?pvs=4",
    },
    // {
    //   type: "html",
    //   value:
    //     "<h3>Unsere Community </h3>  <p>Unsere Community ist ein wichtiger Bestandteil von uns. Hier findest du alle Informationen, die du brauchst, um dich in unserer Community zurechtzufinden.</p> <h4> <a  href='https://youngfounders.network/become-member'>Community Beitreten </a> </h4>",
    // },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
