import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // roadmapSidebar: ["{ type: "autogenerated", dirName: "." }"],
  startupBasicsSidebar: [
    "start",
    {
      type: "category",
      label: "1. Produkt",
      items: [
        "product/find-problem",
        "product/refine-idea",
        "product/research",
        "product/test-idea",
        "product/build-prototype",
        "product/coding",
        "product/product-market-fit",
        "product/business-model",
      ],
    },
    {
      type: "category",
      label: "2. Team",
      items: [
        "team/founding-team",
        "team/shares",
        "team/find-help",
        "team/employees",
        "team/leadership",
      ],
    },
    {
      type: "category",
      label: "3. Growth",
      items: [
        "growth/define-goals",
        "growth/how-can-i-act",
        "growth/impact-startups",
        "growth/marketing",
        "growth/public-relations",
        "growth/sales",
        "growth/Sales Navigator",
      ],
    },
    {
      type: "category",
      label: "4. Finanzierung",
      items: ["funding/funding", "funding/pitching", "funding/venture-capital"],
    },
    {
      type: "category",
      label: "5. Gründung",
      items: [
        "founding/corporate-form",
        "founding/Gründen U18",
        "founding/Geschäftskonto",
        "founding/accounting-and-taxes",
        "founding/Steuerliche Erfassung",
        "founding/Sinnvolle Entscheidungen",
      ],
    },
    {
      type: 'category',
      label: '6. Sales Kurs', 
      items: [
        'sales/1 - Einführung in den B2B Sales Prozess', 
        'sales/2 - Zielgruppenanalyse und ICP (Ideal Customer Profile)', 
        'sales/3 - Cold Outreach Strategie',
        'sales/4 - Lead Qualification und Discovery Calls',
        'sales/5 - Sales Pitch und Demos',
        'sales/6 - Pricing und Verhandlungstaktiken',
        'sales/7 - Abschluss des Deals',
        'sales/8 - After-Sales und Customer Success',
        'sales/9 - Optimierung und Skalierung',
        'sales/10 - Häufige Fehler und Fallstricke im B2B Sales',
        'sales/11 - Nützliche Tools und Ressourcen',
        'sales/A - Deep Dive - Mail Konfiguration',
        'sales/B - Deep Dive - Copywriting',
        'sales/C - Deep Dive - Buying Personas erstellen',
      ],
    },
    {
      type: "link",
      label: "Learn to learn",
      href: "https://www.youtube.com/watch?v=O96fE1E-rf8",
    },
    {
      type: "link",
      label: "Ressources",
      href: "https://joels-code.notion.site/Channels-Courses-6cf8fd0683e447d988538d745ff202ac?pvs=4",
    },
    // {
    //   type: "html",
    //   value:
    //     "<h3>Unsere Community </h3>  <p>Unsere Community ist ein wichtiger Bestandteil von uns. Hier findest du alle Informationen, die du brauchst, um dich in unserer Community zurechtzufinden.</p> <h4> <a  href='https://youngfounders.network/become-member'>Community Beitreten </a> </h4>",
    // },
  ],

  // Zweite Sidebar: yfnSchoolSidebar
  yfnSchoolSidebar: [
    "yfn-school/start",
    {
      type: "category",
      label: "KickOff - Day 1",
      items: [
        "yfn-school/day1/overview",
        "yfn-school/day1/meet&greet",
        "yfn-school/day1/inspiration",
        "yfn-school/day1/mindset",
        "yfn-school/day1/team",
        "yfn-school/day1/break",
        "yfn-school/day1/idea",
        "yfn-school/day1/business-model",
        "yfn-school/day1/summary"
      ],
    },
    {
      type: "category",
      label: "Produkt & Markt - Day 2",
      items: [
        "yfn-school/day2/overview",
        "yfn-school/day2/prototyping",
        "yfn-school/day2/wireframes",
        "yfn-school/day2/market-analysis",
        "yfn-school/day2/feedback",
        "yfn-school/day2/prototype-adjustments",
        "yfn-school/day2/summary",
  
      ],
    },
    {
      type: "category",
      label: "Marketing & Vertrieb - Day 3",
      items: [
        "yfn-school/day3/overview",
        "yfn-school/day3/golden-circle",
        "yfn-school/day3/marketing-strategies",
        "yfn-school/day3/sales-techniques",
        "yfn-school/day3/sales-strategy",
        "yfn-school/day3/summary",
      ],
    },
    {
      type: "category",
      label: "Recht, Finanzen & Pitch - Day 4",
      items: [
        "yfn-school/day4/overview",
        "yfn-school/day4/legal-financial-basics",
        "yfn-school/day4/financial-planning-basics",
        "yfn-school/day4/pitch-intro",
        "yfn-school/day4/pitch-exercises",
        "yfn-school/day4/summary",
      ],
    },
    {
      type: "category",
      label: "DemoDay - Day 5",
      items: [
        "yfn-school/day5/overview",
        "yfn-school/day5/pitch-final",
        "yfn-school/day5/awards-feedback",
        "yfn-school/day5/summary",
      ],
    },
  
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
